# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20160823_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bigaim',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clinicalarea',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clinicaldepartment',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsetting',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='focusarea',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='qi_interest',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='safetytarget',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='suffix',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='guid',
            field=models.CharField(default='c5246dda28784467bdf0f31fe2c67da4', max_length=32, null=True),
        ),
    ]
