# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20161115_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bigaim',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalarea',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldepartment',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalsetting',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='qi_interest',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='safetytarget',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='suffix',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='guid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
