# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20161115_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
